-- AlterTable
ALTER TABLE "User" ADD COLUMN     "CountingDownEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "CountingDownStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "IsCountingDown" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "PhoneConfirmationCode" TEXT DEFAULT '';
